version: 2
updates:
  # Ruby dependencies
  - package-ecosystem: bundler
    directory: /docs
    schedule:
      interval: monthly
  
  - package-ecosystem: github-actions
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: /
    schedule:
      interval: monthly

  # check submodule labs are up-to-date
  - package-ecosystem: gitsubmodule
    directory: /docs
    schedule:
      interval: daily
