# Site details
title: M19581 Data Engineering
description: Course materials for M19581 Data Engineering
url: https://serc-m19581.github.io
gh_repository: https://github.com/SERC-M19581/SERC-M19581.github.io
gh_org: https://github.com/SERC-M19581
moodle_page: https://moodle2.serc.ac.uk/course/view.php?id=28516

# Theme
theme: just-the-docs
color_scheme: serc

# Footer content
# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

mermaid:
  version: "10.1.0"

kramdown:
  syntax_highlighter: rouge
  parse_block_html: true

callouts:
  solution:
    title: Solution
    color: green
callouts_opacity: 0.1

plugins:
  - jekyll-last-modified-at
