# Lint
name: Lint

on:
  # Trigger the workflow on pull requests to main
  pull_request:
    branches: [main]

  # Allows workflow to be run manually from the Actions tab
  workflow_dispatch:

  # enable workflow to be used in other workflows
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: super lint
        uses: github/super-linter/slim@v5
        env:
          # if PR false, else true
          VALIDATE_ALL_CODEBASE: ${{ github.event_name != 'pull_request' }}
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_CSS: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_HTML: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JAVASCRIPT_STANDARD: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_RUBY: true
          VALIDATE_YAML: true
